all: Ex1 Ex2_1 Ex2_2 Ex3_1

test:
	@echo "No auto test"

Ex1:
	python3 ../convertAddr.py Ex1.txt Ex1_compile.txt

Ex2_1:	
	python3 ../convertAddr.py Ex2_1.txt Ex2_1_compile.txt

Ex2_2:
	python3 ../convertAddr.py Ex2_2.txt Ex2_2_compile.txt

Ex3_1:
	python3 ../convertAddr.py Ex3_1.txt Ex3_1_compile.txt

clean:
	rm Ex*_compile.txt