all: Ex5 Ex7 Ex8 Ex9

Ex5:
	python ../convertAddr.py Ex5.txt Ex5_compile.txt

Ex7:
	python ../convertAddr.py Ex7.txt Ex7_compile.txt

Ex8:
	python ../convertAddr.py Ex8.txt Ex8_compile.txt

Ex9:
	python ../convertAddr.py Ex9.txt Ex9_compile.txt

clean:
	rm Ex*_compile.txt